paginate : 5
paginate_path : "/updates/page:num/"
url: "https://py-contributors.github.io" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
site : https://py-contributors.github.io
