name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Welcome to py-contributors to starting new isssue. \n Official Discord https://discord.gg/jJCwJ6Q'' first issue'
        pr-message: 'Welcome to py-contributors to starting new isssue. \n Official Discord https://discord.gg/jJCwJ6Q'' first pr'
